pipeline {
    agent {
        docker {
            image 'selenium-tests'
            args '--user root'
        }
    }

    options {
        timestamps()
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Build") {
            steps {
                sh "mvn clean install -DskipTests"
            }
        }

        stage("Test") {
            steps {
                sh "mvn test -Dheadless=true"
            }
        }
    }

    post {
        always {
            echo "Build completed"
        }
        success {
            echo "Tests passed ✅"
        }
        failure {
            echo "Tests failed ❌"
        }
    }
}