pipeline {
    agent {
        docker {
            image 'selenium/standalone-chrome'
            args '--shm-size=2g'
        }
    }

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Test") {
            steps {
                sh "mvn test -Dheadless=true"
            }
        }
    }
}